"""跨端契约全量导出（G-1.1 契约单一源扩展）。

用法（travel-agent-python 目录下）：
    uv run python scripts/export_contracts.py

产物（全部入库；CI 重跑导出并 git diff 防漂移）：
    contracts/stream_events.schema.json   生成流式事件契约（判别联合，oneOf + const）
    contracts/agent_api.schema.json       Agent 面请求/响应模型（$defs 库）
    contracts/business_api.schema.json    业务面核心端点模型（$defs 库）
    contracts/openapi.json                全量 OpenAPI（main.app，排序键保证字节稳定）
    travel-frontend-vue/src/types/generated/contracts.ts   前端生成类型（唯一允许的契约类型源）

模型取数点：app/schemas/contracts.py 的 CONTRACT_GROUPS（唯一登记处）；
wire 整形（剥 description / 全属性 required）与事件组共用同一实现。
本文件内嵌 JSON Schema → TS 的确定性渲染器：只覆盖本项目 schema 子集
（对象/$ref/anyOf/enum/const/数组/Record），新语法出现时先扩渲染器再改模型。
"""

import json
import sys
from pathlib import Path
from typing import Any, get_args

# 允许脚本独立运行（sys.path[0] 是 scripts/，需补模块根）
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.schemas.contracts import CONTRACT_GROUPS, group_json_schema, models_json_schema_definitions
from app.schemas.stream_events import StreamEvent, export_schema

REPO_ROOT = Path(__file__).resolve().parents[2]
CONTRACTS_DIR = REPO_ROOT / "contracts"
DTS_PATH = REPO_ROOT / "travel-frontend-vue" / "src" / "types" / "generated" / "contracts.ts"

_DTS_HEADER = """\
// AUTO-GENERATED by travel-agent-python/scripts/export_contracts.py — DO NOT EDIT.
// 单一模型源：travel-agent-python/app/schemas/**（登记表 app/schemas/contracts.py）。
// 重新生成：cd travel-agent-python && uv run python scripts/export_contracts.py
// 键名为后端 wire 键（camelCase / 显式别名），与 JSON 序列化结果逐键一致。
"""

_TS_IDENT_FIRST = set("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_$")
_TS_IDENT_REST = _TS_IDENT_FIRST | set("0123456789")
# 属性名命中关键字时一律加引号（"if": string），加引号恒合法
_TS_RESERVED = {
    "break",
    "case",
    "catch",
    "class",
    "const",
    "continue",
    "debugger",
    "default",
    "delete",
    "do",
    "else",
    "enum",
    "export",
    "extends",
    "false",
    "finally",
    "for",
    "function",
    "if",
    "implements",
    "import",
    "in",
    "instanceof",
    "interface",
    "let",
    "new",
    "null",
    "package",
    "private",
    "protected",
    "public",
    "return",
    "static",
    "super",
    "switch",
    "this",
    "throw",
    "true",
    "try",
    "typeof",
    "var",
    "void",
    "while",
    "with",
    "yield",
}


def _is_ident(name: str) -> bool:
    return (
        bool(name)
        and name[0] in _TS_IDENT_FIRST
        and all(c in _TS_IDENT_REST for c in name)
        and name not in _TS_RESERVED
    )


def _ts_type(node: dict[str, Any]) -> str:
    """JSON Schema 节点 → TS 类型表达式（只覆盖本项目产出的 schema 子集）。"""
    if not node:  # pydantic 对 Any/裸容器元素产出空 schema
        return "unknown"
    if "$ref" in node:
        return node["$ref"].rsplit("/", 1)[-1]
    if "const" in node:
        value = node["const"]
        return json.dumps(value, ensure_ascii=False)
    if "enum" in node:
        return " | ".join(json.dumps(v, ensure_ascii=False) for v in node["enum"])
    if "anyOf" in node:
        return " | ".join(_ts_type(member) for member in node["anyOf"])
    schema_type = node.get("type")
    if schema_type == "null":
        return "null"
    if schema_type == "string":
        return "string"
    if schema_type in ("integer", "number"):
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "array":
        items = node.get("items")
        inner = _ts_type(items) if isinstance(items, dict) else "unknown"
        if " " in inner:
            inner = f"({inner})"
        return f"{inner}[]"
    if schema_type == "object":
        if "properties" in node:
            return _ts_object_literal(node)
        additional = node.get("additionalProperties")
        value_type = _ts_type(additional) if isinstance(additional, dict) else "unknown"
        return f"Record<string, {value_type}>"
    raise ValueError(f"unsupported schema node in TS emitter: {json.dumps(node, ensure_ascii=False)[:200]}")


def _ts_object_literal(node: dict[str, Any]) -> str:
    """匿名对象字面量（嵌套 inline object）→ `{ key: type; ... }`。"""
    props = node.get("properties", {})
    required = set(node.get("required", props.keys()))
    fields = []
    for key, prop_schema in props.items():
        opt = "" if key in required else "?"
        name = key if _is_ident(key) else json.dumps(key, ensure_ascii=False)
        fields.append(f"{name}{opt}: {_ts_type(prop_schema)}")
    return "{ " + "; ".join(fields) + " }" if fields else "Record<string, unknown>"


def _emit_interface(name: str, schema: dict[str, Any]) -> str:
    if schema.get("type") != "object" or "properties" not in schema:
        # 非对象 def（本项目现状不产生，防御性输出为类型别名）
        return f"export type {name} = {_ts_type(schema)}\n"
    props = schema["properties"]
    required = set(schema.get("required", props.keys()))
    lines = [f"export interface {name} {{"]
    for key, prop_schema in props.items():
        opt = "" if key in required else "?"
        name_ts = key if _is_ident(key) else json.dumps(key, ensure_ascii=False)
        lines.append(f"  {name_ts}{opt}: {_ts_type(prop_schema)}")
    lines.append("}")
    return "\n".join(lines) + "\n"


def _stream_event_members() -> list[type]:
    """从 StreamEvent 判别联合提取成员模型（避免在脚本里硬编码事件清单）。"""
    union = get_args(StreamEvent)[0]
    return list(get_args(union))


def render_ts() -> str:
    """渲染前端生成类型文件（分区 = 契约组；声明顺序 = 登记顺序，字节稳定）。"""
    from app.schemas.contracts import mark_all_properties_required, strip_descriptions

    sections: list[str] = [_DTS_HEADER]
    seen: set[str] = set()

    def emit(definitions: dict[str, dict[str, Any]]) -> None:
        strip_descriptions(definitions)
        mark_all_properties_required(definitions)
        for name, schema in definitions.items():
            if name in seen:
                continue
            seen.add(name)
            sections.append(_emit_interface(name, schema))

    for group in ("agent_api", "business_api"):
        sections.append(f"// ===== {group} =====")
        emit(models_json_schema_definitions(CONTRACT_GROUPS[group]))

    sections.append("// ===== stream_events（JSON Lines 事件）=====")
    members = _stream_event_members()
    emit(models_json_schema_definitions(tuple(members)))
    sections.append("export type StreamEvent = " + " | ".join(m.__name__ for m in members) + "\n")

    return "\n".join(sections)


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"exported {path}")


def _dump(path: Path, payload: dict) -> None:
    _write(path, json.dumps(payload, ensure_ascii=False, indent=2) + "\n")


def main() -> None:
    _dump(CONTRACTS_DIR / "stream_events.schema.json", export_schema())
    for group in CONTRACT_GROUPS:
        _dump(CONTRACTS_DIR / f"{group}.schema.json", group_json_schema(group))

    # 全量 OpenAPI：整只 main.app（含全部路由与挂载方式），排序键保证字节稳定。
    # main 的 import 有外部客户端初始化成本，测试环境由 conftest 统一兜底。
    from main import app

    _dump(CONTRACTS_DIR / "openapi.json", app.openapi())
    _write(DTS_PATH, render_ts())


if __name__ == "__main__":
    main()
